version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: payment_service
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - DATABASE_DSN=postgresql://admin:admin123@postgres:5432/payment_service?sslmode=disable
      - JWT_SECRET=your-secret-key-here
    volumes:
      - .:/app

volumes:
  postgres_data:
